# Generated by Django 3.2.8 on 2021-11-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Vehicle model')),
                ('vehicle_image', models.ImageField(upload_to='event_images/')),
                ('vehicle_text', models.CharField(max_length=300)),
                ('mileage_per_day', models.CharField(max_length=10, verbose_name='mileage_per_day')),
                ('mileage_per_year', models.CharField(max_length=10, verbose_name='mileage_per_year')),
                ('number_of_tech_actions', models.CharField(max_length=10, verbose_name='number_of_tech_actions')),
                ('fuel_consumption', models.CharField(max_length=10, verbose_name='fuel_consumption')),
                ('number_of_failures', models.CharField(max_length=10, verbose_name='number_of_failures')),
            ],
        ),
    ]
